refactor(Toast): 新增主题色支持
TaleLin/lin-ui pull request #1228
Opened 2020-12-28 07:32 UTC by murongg

2020-12-28 14:15 UTC, juzi214032 requested changes

2020-12-28 14:15 UTC, juzi214032 commented on src/toast/index.wxml
> +      color="{{iconColor? iconColor: ''}}"
这里直接写成`color="{{iconColor}}"`就可以了

2020-12-28 14:15 UTC, juzi214032 commented on src/toast/index.less
> +  color: #ffffff;
加了一个 color 是为什么

2020-12-29 03:25 UTC, murongg commented on src/toast/index.less
> +  color: #ffffff;
默认颜色

2021-01-01 12:54 UTC, juzi214032 approved these changes
LGTM

2021-01-01 12:54 UTC, merged